apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: zilcherry100/react-app:a0e0cb4cbf0adc2841731b91c4971c0e7aefe2d6
        ports:
        - containerPort: 80
